---
- name: Test name
  hosts: all
  tasks:
  - name: Get jitsi meet from s3
    amazon.aws.aws_s3:
      bucket: "{{ BUCKET_LOCATION }}"
      object: "{{ OBJECT_LOCATION }}"
      dest: /tmp/jm.zip
      mode: get
      overwrite: different
    tags:
      - workcast_assets
  - name: Unarchive jitsi meet
    unarchive:
      src: /tmp/jm.zip
      dest: /usr/share/jitsi-meet
      remote_src: yes
      group: root
      owner: root
      mode: 750
    tags:
      - workcast_assets