---
- name: Test name
  hosts: all
  tasks:
  - name: Get jitsi meet from s3
    amazon.aws.aws_s3:
      bucket: "{{ BUCKET_LOCATION }}"
      object: "{{ OBJECT_LOCATION }}"
      dest: /tmp/jm.zip
      mode: get
      overwrite: different
    tags:
      - workcast_assets
  - name: Remove all file from existing repo
    shell: rm -rf /usr/share/jitsi-meet/*
    tags:
      - workcast_assets
  - name: Unarchive jitsi meet
    unarchive:
      src: /tmp/jm.zip
      dest: /usr/share/jitsi-meet

      group: root
      owner: root
      mode: 0750
    tags:
      - workcast_assets